# Name of the workflow
name: My Test Workflow

# Define the trigger event
on: [push]

# Jobs that the workflow will run

jobs: 
    say-hello:
        runs-on: ubuntu-latest
        steps:
            - name: Say Hello
              run: echo "Hello, GitHub Actions"
    
    # Job to build the C code
    build-and-test:
        needs: [say-hello]
        runs-on: ubuntu-latest
        steps:
                - name: Check out this repo
                  uses: actions/checkout@v3

                - name: Install Dependencies
                  run: sudo apt install -y build-essential python3
                
                - run: pwd

                - name: Run test
                  run: python3 test.py
